//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class adres
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public adres()
        {
            this.kutuphane = new HashSet<kutuphane>();
            this.yayinEvi = new HashSet<yayinEvi>();
        }
    
        public int adres_id { get; set; }
        public string cadde { get; set; }
        public string sokak { get; set; }
        public string mahalle { get; set; }
        public string binaAd { get; set; }
        public string binaNo { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<kutuphane> kutuphane { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<yayinEvi> yayinEvi { get; set; }
    }
}
