//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kutuphane1Entities1 : DbContext
    {
        public Kutuphane1Entities1()
            : base("name=Kutuphane1Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<adres> adres { get; set; }
        public virtual DbSet<altBaslik> altBaslik { get; set; }
        public virtual DbSet<emanet> emanet { get; set; }
        public virtual DbSet<kitapKategori> kitapKategori { get; set; }
        public virtual DbSet<kitaplar> kitaplar { get; set; }
        public virtual DbSet<kutuphane> kutuphane { get; set; }
        public virtual DbSet<odeme> odeme { get; set; }
        public virtual DbSet<raf> raf { get; set; }
        public virtual DbSet<salon> salon { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ustBaslik> ustBaslik { get; set; }
        public virtual DbSet<uyeler> uyeler { get; set; }
        public virtual DbSet<uyeTip> uyeTip { get; set; }
        public virtual DbSet<yayinEvi> yayinEvi { get; set; }
        public virtual DbSet<yayinTipi> yayinTipi { get; set; }
    }
}
