//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class odeme
    {
        public int odeme_id { get; set; }
        public System.DateTime tarih { get; set; }
        public double tutar { get; set; }
        public int uye_id { get; set; }
    
        public virtual uyeler uyeler { get; set; }
    }
}
