//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uyeler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public uyeler()
        {
            this.emanet = new HashSet<emanet>();
            this.odeme = new HashSet<odeme>();
        }
    
        public int uye_id { get; set; }
        public string uyeAd { get; set; }
        public string uyeSoyad { get; set; }
        public string telefon { get; set; }
        public string tcNo { get; set; }
        public string eposta { get; set; }
        public string kullaniciAdi { get; set; }
        public string kullaniciSifre { get; set; }
        public int uyeTip_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<emanet> emanet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<odeme> odeme { get; set; }
        public virtual uyeTip uyeTip { get; set; }
    }
}
